# Generated by Django 5.2.8 on 2025-11-11 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="The question or instruction, e.g., 'Match countries with their capitals'"
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=10, help_text="Points per correct match"
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=60, help_text="Time limit in seconds"
                    ),
                ),
                (
                    "left_items",
                    models.JSONField(
                        help_text="List of items on the left side to drag from"
                    ),
                ),
                (
                    "right_items",
                    models.JSONField(
                        help_text="List of items on the right side to drop to"
                    ),
                ),
                (
                    "correct_matches",
                    models.JSONField(
                        help_text="Dictionary mapping left item indices to right item indices"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Optional explanation shown after answering",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_assign_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssignQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Drag & Drop Quiz", max_length=200)),
                ("room_code", models.CharField(blank=True, max_length=4, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("question_start_time", models.DateTimeField(blank=True, null=True)),
                ("max_participants", models.IntegerField(default=50)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_assign_quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_in_assign_quiz",
                        to="Assign.assignquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssignParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_score", models.IntegerField(default=0)),
                ("questions_answered", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="Assign.assignquiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_score", "name"],
                "unique_together": {("quiz", "name")},
            },
        ),
        migrations.CreateModel(
            name="AssignSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_question_number", models.IntegerField(default=0)),
                ("total_questions_sent", models.IntegerField(default=0)),
                ("is_question_active", models.BooleanField(default=False)),
                ("question_end_time", models.DateTimeField(blank=True, null=True)),
                ("total_responses_current_question", models.IntegerField(default=0)),
                ("average_score_current_question", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="Assign.assignquiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssignAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_matches",
                    models.JSONField(
                        help_text="Dictionary mapping left item indices to right item indices"
                    ),
                ),
                ("points_earned", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_taken",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to answer in seconds",
                        null=True,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assign_answers",
                        to="Assign.assignparticipant",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assign_answers",
                        to="Assign.assignquestion",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assign_answers",
                        to="Assign.assignquiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("quiz", "participant", "question")},
            },
        ),
    ]
