# Generated by Django 5.2.8 on 2025-11-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0002_assignquiz_selected_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignquestion",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this question is active and can be used in quizzes",
            ),
        ),
    ]
