# Generated by Django 6.0.2 on 2026-04-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0008_assignquiz_question_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignquiz",
            name="round_based",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignsession",
            name="current_round_index",
            field=models.IntegerField(default=0),
        ),
    ]
