# Generated by Django 6.0.2 on 2026-04-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0009_add_round_based_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignquiz",
            name="round_based",
            field=models.BooleanField(default=True),
        ),
    ]
