# Generated by Django 6.0.2 on 2026-04-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0011_set_existing_round_based_true"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignquiz",
            name="round_based",
        ),
    ]
