# Generated by Django 5.2.8 on 2025-11-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("who_is_that", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whothatquiz",
            name="selected_questions",
            field=models.ManyToManyField(
                blank=True, related_name="quizzes", to="who_is_that.whothatquestion"
            ),
        ),
    ]
