# Generated by Django 5.2.8 on 2026-02-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("who_is_that", "0003_alter_whothatparticipant_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whothatanswer",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whothatanswer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="whothatparticipant",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whothatparticipant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="whothatquestion",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whothatquestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="whothatquiz",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whothatquiz",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="whothatsession",
            name="synced",
            field=models.BooleanField(default=False),
        ),
    ]
