# Generated by Django 5.2.3 on 2025-06-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='join_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='name',
            field=models.CharField(default='Mein Quiz', max_length=100),
        ),
    ]
