# Generated by Django 5.2.3 on 2025-06-30 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quizsession_join_code_quizsession_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='wrong_answer_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='wrong_answer_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='wrong_answer_3',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mc', 'Multiple Choice'), ('text', 'Freitext'), ('slider', 'Slider (Schätzfrage)')], default='mc', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='slider_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='slider_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='slider_solution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='slider_tolerance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantanswer',
            name='chosen_answer',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.category'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz_app.question')),
            ],
        ),
    ]
