# Generated by Django 5.2.3 on 2025-06-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_category_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantanswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
