# Generated by Django 5.2.3 on 2025-07-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_participantanswer_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
