# Generated by Django 5.2.3 on 2025-07-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_category_points_alter_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_text_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slider_max',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slider_min',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slider_solution',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slider_tolerance',
        ),
        migrations.AddField(
            model_name='participant',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
