# Generated by Django 5.2.3 on 2025-07-06 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_remove_question_correct_text_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='name',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='Placeholder', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizsession',
            name='categories',
            field=models.ManyToManyField(blank=True, to='quiz_app.category'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='participants',
            field=models.ManyToManyField(related_name='quiz_sessions', to='quiz_app.participant'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quiz_sessions', to='quiz_app.question'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_sessions', to='quiz_app.question'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
