# Generated by Django 5.2.3 on 2025-07-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_remove_quizsession_is_active_remove_quizsession_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
