# Generated by Django 5.2.3 on 2025-07-13 20:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_quizsession_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='current_question',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='category',
            name='points',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='participant_id',
        ),
        migrations.RemoveField(
            model_name='participantanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='participantanswer',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='participantanswer',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='Placeholder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='wrong_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='participantanswer',
            name='chosen_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participantanswer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participantanswer',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_app.participant'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_code', models.UUIDField(editable=False, unique=True)),
                ('join_code', models.CharField(max_length=4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_sessions', to='quiz_app.question')),
            ],
        ),
        migrations.AlterField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quiz_app.session'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='QuizSession',
        ),
    ]
