# Generated by Django 5.2.3 on 2025-07-13 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_remove_quizsession_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ended_at',
        ),
        migrations.AlterField(
            model_name='session',
            name='session_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
