# Generated by Django 5.2.3 on 2025-07-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0010_remove_session_created_at_remove_session_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.question'),
        ),
    ]
