# Generated by Django 5.1.6 on 2025-08-02 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0011_alter_participantanswer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-points', 'name']},
        ),
        migrations.AlterModelOptions(
            name='participantanswer',
            options={'ordering': ['submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category', 'question_text']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='participantanswer',
            unique_together={('participant', 'question')},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_connected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='participantanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participantanswer',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participantanswer',
            name='time_taken',
            field=models.FloatField(blank=True, help_text='Time in seconds to answer', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation for the correct answer', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=100, help_text='Points awarded for correct answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=30, help_text='Time limit in seconds'),
        ),
        migrations.AddField(
            model_name='session',
            name='allow_late_joins',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='auto_advance',
            field=models.BooleanField(default=False, help_text='Auto advance to next question'),
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='session',
            name='current_question_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='Quiz Session', max_length=200),
        ),
        migrations.AddField(
            model_name='session',
            name='question_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='show_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='show_correct_answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='show_leaderboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting to Start'), ('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participantanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_answers', to='quiz_app.question'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('session', 'name')},
        ),
        migrations.RemoveField(
            model_name='participantanswer',
            name='points',
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.session')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
