# Generated by Django 5.2.8 on 2026-02-16 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SortingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synced", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=200)),
                (
                    "correct_rank",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Lower numbers come first",
                        max_digits=10,
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["correct_rank"],
            },
        ),
        migrations.CreateModel(
            name="SortingLadderGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synced", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="Sorting Ladder", max_length=200)),
                ("room_code", models.CharField(blank=True, max_length=4, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("max_participants", models.IntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_sorting_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SortingLadderParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synced", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_eliminated", models.BooleanField(default=False)),
                ("total_score", models.IntegerField(default=0)),
                ("rounds_survived", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "hub_session_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=16, null=True
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="sorting_ladder.sortingladdergame",
                    ),
                ),
            ],
            options={
                "ordering": ["-rounds_survived", "name"],
                "unique_together": {("quiz", "name", "hub_session_code")},
            },
        ),
        migrations.CreateModel(
            name="SortingLadderSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synced", models.BooleanField(default=False)),
                ("current_round", models.PositiveIntegerField(default=0)),
                ("is_round_active", models.BooleanField(default=False)),
                ("round_start_time", models.DateTimeField(blank=True, null=True)),
                ("round_end_time", models.DateTimeField(blank=True, null=True)),
                ("time_limit_seconds", models.IntegerField(default=30)),
                ("shuffled_item_ids", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_element",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_as_active",
                        to="sorting_ladder.sortingitem",
                    ),
                ),
                (
                    "placed_elements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sessions_as_placed",
                        to="sorting_ladder.sortingitem",
                    ),
                ),
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="sorting_ladder.sortingladdergame",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SortingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synced", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_text", models.TextField()),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Instructions for the players"
                    ),
                ),
                ("points", models.IntegerField(default=10)),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=30, help_text="Time limit in seconds"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_sorting_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="sortingladdergame",
            name="current_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_in_games",
                to="sorting_ladder.sortingquestion",
            ),
        ),
        migrations.AddField(
            model_name="sortingladdergame",
            name="selected_questions",
            field=models.ManyToManyField(
                blank=True, related_name="games", to="sorting_ladder.sortingquestion"
            ),
        ),
        migrations.AddField(
            model_name="sortingitem",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="sorting_ladder.sortingquestion",
            ),
        ),
        migrations.CreateModel(
            name="RoundSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synced", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "all_elements",
                    models.JSONField(
                        default=list,
                        help_text="List of all elements submitted in that round",
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="sorting_ladder.sortingladdergame",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="sorting_ladder.sortingladderparticipant",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="sorting_ladder.sortingquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="sortingitem",
            unique_together={("topic", "correct_rank")},
        ),
    ]
