# Generated by Django 5.2.11 on 2026-02-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorting_ladder", "0002_remove_sortingquestion_time_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sortingquestion",
            name="lower_label",
            field=models.CharField(
                default="Descending",
                help_text="Label representing the lowest extreme (e.g., Smallest, Youngest, Lowest)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="sortingquestion",
            name="upper_label",
            field=models.CharField(
                default="Ascending",
                help_text="Label representing the highest extreme (e.g., Largest, Oldest, Highest)",
                max_length=50,
            ),
        ),
    ]
