# Generated by Django 5.2.8 on 2025-11-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("where_is_this", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wherequiz",
            name="selected_questions",
            field=models.ManyToManyField(
                blank=True, related_name="quizzes", to="where_is_this.wherequestion"
            ),
        ),
    ]
