# Generated by Django 5.2.8 on 2025-11-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("black_jack_quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blackjackquiz",
            name="selected_questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="quizzes",
                to="black_jack_quiz.blackjackquestion",
            ),
        ),
    ]
