# Generated by Django 6.0.2 on 2026-04-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("black_jack_quiz", "0005_blackjackbundle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blackjackquestion",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="blackjackquestion",
            name="hint_text",
        ),
    ]
