# Generated by Django 5.2.8 on 2025-11-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QuizGame", "0002_quizquestion_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="selected_questions",
            field=models.ManyToManyField(
                blank=True, related_name="quizzes", to="QuizGame.quizquestion"
            ),
        ),
    ]
