# Generated by Django 5.2.8 on 2026-02-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QuizGame", "0004_alter_quizparticipant_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quiz",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="quizparticipant",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizparticipant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="quizsession",
            name="synced",
            field=models.BooleanField(default=False),
        ),
    ]
