# Generated by Django 5.2.11 on 2026-02-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorting_ladder", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sortingquestion",
            name="time_limit",
        ),
        migrations.AddField(
            model_name="sortingquestion",
            name="round_time_limit",
            field=models.PositiveIntegerField(
                default=30, help_text="Per-round time limit in seconds"
            ),
        ),
    ]
