# Generated by Django 5.2.8 on 2025-11-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assign", "0003_assignquestion_is_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assignparticipant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="assignparticipant",
            name="hub_session_code",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="assignparticipant",
            unique_together={("quiz", "name", "hub_session_code")},
        ),
    ]
