# Generated by Django 5.2.8 on 2025-11-11 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstimationQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="The question, e.g., 'How tall is Mount Everest?'"
                    ),
                ),
                (
                    "correct_answer",
                    models.FloatField(help_text="The correct numerical answer"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("number", "Number (no unit)"),
                            ("meters", "Meters"),
                            ("kilometers", "Kilometers"),
                            ("feet", "Feet"),
                            ("inches", "Inches"),
                            ("centimeters", "Centimeters"),
                            ("years", "Years"),
                            ("months", "Months"),
                            ("days", "Days"),
                            ("hours", "Hours"),
                            ("minutes", "Minutes"),
                            ("seconds", "Seconds"),
                            ("kilograms", "Kilograms"),
                            ("pounds", "Pounds"),
                            ("grams", "Grams"),
                            ("tons", "Tons"),
                            ("liters", "Liters"),
                            ("gallons", "Gallons"),
                            ("milliliters", "Milliliters"),
                            ("degrees", "Degrees"),
                            ("fahrenheit", "Fahrenheit"),
                            ("celsius", "Celsius"),
                            ("dollars", "Dollars ($)"),
                            ("euros", "Euros (€)"),
                            ("percent", "Percent (%)"),
                            ("people", "People"),
                            ("calories", "Calories"),
                            ("watts", "Watts"),
                            ("miles", "Miles"),
                            ("mph", "Miles per hour"),
                            ("kmh", "Kilometers per hour"),
                        ],
                        default="number",
                        help_text="Unit of measurement",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "max_points",
                    models.PositiveIntegerField(
                        default=100, help_text="Maximum points for perfect answer"
                    ),
                ),
                (
                    "tolerance_percentage",
                    models.FloatField(
                        default=10.0,
                        help_text="Tolerance percentage for full points (1-50%)",
                    ),
                ),
                (
                    "hint_text",
                    models.TextField(
                        blank=True,
                        help_text="Optional hint shown during question",
                        null=True,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Optional explanation shown after answering",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_estimation_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EstimationQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Estimation Quiz", max_length=200)),
                ("room_code", models.CharField(blank=True, max_length=4, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("question_start_time", models.DateTimeField(blank=True, null=True)),
                ("max_participants", models.IntegerField(default=50)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_estimation_quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_in_estimation_quiz",
                        to="Estimation.estimationquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EstimationParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_score", models.IntegerField(default=0)),
                ("questions_answered", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="Estimation.estimationquiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_score", "name"],
                "unique_together": {("quiz", "name")},
            },
        ),
        migrations.CreateModel(
            name="EstimationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_question_number", models.IntegerField(default=0)),
                ("total_questions_sent", models.IntegerField(default=0)),
                ("is_question_active", models.BooleanField(default=False)),
                ("question_end_time", models.DateTimeField(blank=True, null=True)),
                ("total_responses_current_question", models.IntegerField(default=0)),
                ("average_score_current_question", models.FloatField(default=0)),
                ("average_accuracy_current_question", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="Estimation.estimationquiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstimationAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_answer",
                    models.FloatField(help_text="The participant's numerical answer"),
                ),
                ("points_earned", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_taken",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to answer in seconds",
                        null=True,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimation_answers",
                        to="Estimation.estimationparticipant",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimation_answers",
                        to="Estimation.estimationquestion",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimation_answers",
                        to="Estimation.estimationquiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("quiz", "participant", "question")},
            },
        ),
    ]
