# Generated by Django 5.2.8 on 2025-12-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estimation", "0003_alter_estimationparticipant_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimationquiz",
            name="scoring_mode",
            field=models.CharField(
                choices=[("tolerance", "Tolerance Mode"), ("rank", "Rank Mode")],
                default="tolerance",
                max_length=16,
            ),
        ),
    ]
