# Generated by Django 5.2.8 on 2026-02-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estimation", "0004_estimationquiz_scoring_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimationanswer",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="estimationanswer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="estimationparticipant",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="estimationparticipant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="estimationquestion",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="estimationquestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="estimationquiz",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="estimationquiz",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="estimationsession",
            name="synced",
            field=models.BooleanField(default=False),
        ),
    ]
