# Generated by Django 5.2.8 on 2025-11-11 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhoQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statement",
                    models.TextField(
                        help_text="The statement that may be true or false for different people"
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=10, help_text="Points per correct identification"
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=60, help_text="Time limit in seconds"
                    ),
                ),
                (
                    "people",
                    models.JSONField(
                        help_text="List of people with their names and whether they are lying"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Optional explanation shown after answering",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_who_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhoQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Who is Lying?", max_length=200)),
                ("room_code", models.CharField(blank=True, max_length=4, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("question_start_time", models.DateTimeField(blank=True, null=True)),
                ("max_participants", models.IntegerField(default=50)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_who_quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_in_who_quiz",
                        to="who_is_lying.whoquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhoParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_score", models.IntegerField(default=0)),
                ("questions_answered", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="who_is_lying.whoquiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_score", "name"],
                "unique_together": {("quiz", "name")},
            },
        ),
        migrations.CreateModel(
            name="WhoSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_question_number", models.IntegerField(default=0)),
                ("total_questions_sent", models.IntegerField(default=0)),
                ("is_question_active", models.BooleanField(default=False)),
                ("question_end_time", models.DateTimeField(blank=True, null=True)),
                ("total_responses_current_question", models.IntegerField(default=0)),
                ("average_score_current_question", models.FloatField(default=0)),
                ("average_accuracy_current_question", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="who_is_lying.whoquiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WhoAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_liars",
                    models.JSONField(
                        help_text="List of indices of people selected as liars"
                    ),
                ),
                ("points_earned", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_taken",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to answer in seconds",
                        null=True,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="who_answers",
                        to="who_is_lying.whoparticipant",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="who_answers",
                        to="who_is_lying.whoquestion",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="who_answers",
                        to="who_is_lying.whoquiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("quiz", "participant", "question")},
            },
        ),
    ]
