# Generated by Django 5.2.8 on 2025-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("who_is_lying", "0003_whoquiz_selected_questions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="whoparticipant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="whoparticipant",
            name="hub_session_code",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="whoparticipant",
            unique_together={("quiz", "name", "hub_session_code")},
        ),
    ]
