# Generated by Django 5.2.8 on 2025-11-11 08:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HubSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("current_step_index", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="HubParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=50)),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="games_hub.hubsession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "nickname")},
            },
        ),
        migrations.CreateModel(
            name="HubGameStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "game_key",
                    models.CharField(
                        choices=[
                            ("quiz", "QuizGame"),
                            ("assign", "Assign"),
                            ("estimation", "Estimation"),
                            ("where", "Where Is This"),
                            ("who", "Who Is Lying"),
                            ("who_that", "Who Is That"),
                            ("blackjack", "Black Jack Quiz"),
                        ],
                        max_length=20,
                    ),
                ),
                ("room_code", models.CharField(blank=True, max_length=16)),
                ("title", models.CharField(blank=True, max_length=100)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="games_hub.hubsession",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("session", "order")},
            },
        ),
    ]
