# Generated by Django 5.2.8 on 2026-02-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games_hub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubgamestep",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hubgamestep",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="hubparticipant",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hubparticipant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="hubsession",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hubsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
