# Generated by Django 5.2.11 on 2026-02-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games_hub", "0002_hubgamestep_synced_hubgamestep_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubsession",
            name="games_weight",
            field=models.FloatField(default=2.0),
        ),
    ]
