# Generated by Django 6.0.2 on 2026-03-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games_hub", "0003_hubsession_games_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubparticipant",
            name="score_adjustment",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="hubgamestep",
            name="game_key",
            field=models.CharField(
                choices=[
                    ("quiz", "QuizGame"),
                    ("assign", "Assign"),
                    ("estimation", "Estimation"),
                    ("where", "Where Is This"),
                    ("who", "Who Is Lying"),
                    ("who_that", "Who Is That"),
                    ("blackjack", "Black Jack Quiz"),
                    ("sorting_ladder", "Sorting Ladder"),
                ],
                max_length=20,
            ),
        ),
    ]
