# Generated by Django 6.0.2 on 2026-03-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games_hub", "0005_gamevote"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubsession",
            name="scoreboard_visible",
            field=models.BooleanField(default=False),
        ),
    ]
