# Generated by Django 6.0.2 on 2026-04-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games_hub", "0006_hubsession_scoreboard_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubgamestep",
            name="game_key",
            field=models.CharField(
                choices=[
                    ("quiz", "QuizGame"),
                    ("assign", "Assign"),
                    ("estimation", "Estimation"),
                    ("where", "Where Is This"),
                    ("who", "Who Is Lying"),
                    ("who_that", "Who Is That"),
                    ("blackjack", "Black Jack Quiz"),
                    ("sorting_ladder", "Sorting Ladder"),
                    ("clue_rush", "Clue Rush"),
                ],
                max_length=20,
            ),
        ),
    ]
