# Generated by Django 5.2.8 on 2026-01-19 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClueQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("points", models.IntegerField(default=10)),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=30, help_text="Time limit in seconds"
                    ),
                ),
                ("answer", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_clue_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Clue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clue_text", models.TextField()),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Clue order (1 = first clue)"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=10, help_text="Seconds this clue stays visible"
                    ),
                ),
                (
                    "clue_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clues",
                        to="clue_rush.cluequestion",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("clue_question", "order")},
            },
        ),
        migrations.CreateModel(
            name="ClueRushGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Clue Rush", max_length=200)),
                ("room_code", models.CharField(blank=True, max_length=4, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("max_participants", models.IntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("clue_start_time", models.DateTimeField(blank=True, null=True)),
                ("question_start_time", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_cluerush_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_clue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_in_games",
                        to="clue_rush.clue",
                    ),
                ),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_in_games",
                        to="clue_rush.cluequestion",
                    ),
                ),
                (
                    "selected_questions",
                    models.ManyToManyField(
                        blank=True, related_name="games", to="clue_rush.cluequestion"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClueRushParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_score", models.IntegerField(default=0)),
                ("questions_answered", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "hub_session_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=16, null=True
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="clue_rush.cluerushgame",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_score", "name"],
                "unique_together": {("quiz", "name", "hub_session_code")},
            },
        ),
        migrations.CreateModel(
            name="ClueRushSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_questions_sent", models.PositiveIntegerField(default=0)),
                ("current_question_number", models.PositiveIntegerField(default=0)),
                ("is_question_active", models.BooleanField(default=False)),
                ("question_end_time", models.DateTimeField(blank=True, null=True)),
                ("current_clue_number", models.PositiveIntegerField(default=0)),
                ("is_clue_active", models.BooleanField(default=False)),
                ("clue_end_time", models.DateTimeField(blank=True, null=True)),
                ("total_responses_current_question", models.IntegerField(default=0)),
                ("correct_responses_current_question", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="clue_rush.cluerushgame",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClueAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.CharField(max_length=200)),
                ("is_correct", models.BooleanField(default=False)),
                ("points_earned", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_taken",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to answer in seconds",
                        null=True,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clue_answers",
                        to="clue_rush.cluequestion",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clue_answers",
                        to="clue_rush.cluerushgame",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clue_answers",
                        to="clue_rush.cluerushparticipant",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("quiz", "participant", "question")},
            },
        ),
    ]
