# Generated by Django 5.2.8 on 2026-02-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clue_rush", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clue",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="clueanswer",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clueanswer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cluequestion",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cluequestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cluerushgame",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cluerushgame",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cluerushparticipant",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cluerushparticipant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cluerushsession",
            name="synced",
            field=models.BooleanField(default=False),
        ),
    ]
