# Generated by Django 6.0.2 on 2026-04-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clue_rush", "0004_cluerushgame_question_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluequestion",
            name="participant_question",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Frage, die Teilnehmern oberhalb des Antwort-Feldes angezeigt wird",
                max_length=300,
            ),
        ),
    ]
