# Generated by Django 6.0.2 on 2026-04-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clue_rush", "0005_add_participant_question_to_cluequestion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluequestion",
            name="participant_question",
        ),
    ]
