# Generated by Django 5.2.8 on 2025-11-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("who_is_lying", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whoquestion",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
