# Generated by Django 5.2.8 on 2026-02-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("who_is_lying", "0004_alter_whoparticipant_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whoanswer",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whoanswer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="whoparticipant",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whoparticipant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="whoquestion",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whoquestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="whoquiz",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whoquiz",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="whosession",
            name="synced",
            field=models.BooleanField(default=False),
        ),
    ]
