# Generated by Django 5.2.8 on 2025-11-11 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackJackQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="The question, e.g., 'How many legs does a spider have?'"
                    ),
                ),
                (
                    "correct_answer",
                    models.IntegerField(
                        help_text="The correct numerical answer (integer only)"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=30, help_text="Time limit in seconds"
                    ),
                ),
                (
                    "hint_text",
                    models.TextField(
                        blank=True,
                        help_text="Optional hint shown during question",
                        null=True,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Optional explanation shown after answering",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_blackjack_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlackJackQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Black Jack Quiz", max_length=200)),
                ("room_code", models.CharField(blank=True, max_length=4, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("current_question_number", models.IntegerField(default=0)),
                ("question_start_time", models.DateTimeField(blank=True, null=True)),
                ("max_participants", models.IntegerField(default=50)),
                ("total_questions", models.IntegerField(default=5)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_blackjack_quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_in_blackjack_quiz",
                        to="black_jack_quiz.blackjackquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlackJackParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_points", models.IntegerField(default=0)),
                ("questions_answered", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_busted", models.BooleanField(default=False)),
                ("final_score", models.IntegerField(default=0)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="black_jack_quiz.blackjackquiz",
                    ),
                ),
            ],
            options={
                "ordering": ["final_score", "name"],
                "unique_together": {("quiz", "name")},
            },
        ),
        migrations.CreateModel(
            name="BlackJackSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_question_number", models.IntegerField(default=0)),
                ("total_questions_sent", models.IntegerField(default=0)),
                ("is_question_active", models.BooleanField(default=False)),
                ("question_end_time", models.DateTimeField(blank=True, null=True)),
                ("total_responses_current_question", models.IntegerField(default=0)),
                ("average_points_current_question", models.FloatField(default=0)),
                ("busted_participants_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="black_jack_quiz.blackjackquiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlackJackAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_answer",
                    models.IntegerField(help_text="The participant's numerical answer"),
                ),
                ("points_earned", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_taken",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to answer in seconds",
                        null=True,
                    ),
                ),
                ("question_number", models.IntegerField(default=1)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blackjack_answers",
                        to="black_jack_quiz.blackjackparticipant",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blackjack_answers",
                        to="black_jack_quiz.blackjackquestion",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blackjack_answers",
                        to="black_jack_quiz.blackjackquiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("quiz", "participant", "question")},
            },
        ),
    ]
